# Generated by Django 2.2.4 on 2019-08-09 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RemoteServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remote_server_ip', models.CharField(max_length=15, verbose_name='Remote Server Ip')),
                ('port', models.CharField(max_length=5, verbose_name='Port')),
                ('is_active', models.BooleanField(default=False, verbose_name='Activity')),
            ],
        ),
    ]
